savoirfairelinux/cqfd

README.md
It is easy for new users to trip over an SSH credential problem as the
username in the builder is different so make the trick easier to find.
Signed-off-by: Ash Charles <ash.charles@savoirfairelinux.com>
=> Add notes on SSH handling to readme

cqfd
Currently, the files property is not ready for a multiline
value.
Example of a multiline files property:
files='README.html \
README.doc'
The configuration above results in the following shell error:
cqfd: fatal: Cannot create release: missing \
The `\' is not escaped and cqfd tries to test existence of a
file named `\' which does not exists.
This patch evaluates an echo fo the $files variable and
stores the output to $release_files variable.
Signed-off-by: Gaël PORTAY <gael.portay@savoirfairelinux.com>
=> cqfd: allow multiline for files

cqfd
The ini-to-shell function is a nice but complicated trick.
It plays with bash arrays to translate an ini-style file into shell
scripting.
In this way, the following ini section
[build]
command='configure --enable-debug --extra-cflags=-I/usr/include && \
--extra-ldflags=-L/usr/lib && \
make'
is translated into the following shell
cfg.section.build () {
command=( 'configure --enable-debug --extra-cflags=-I/usr/include &&  \
--extra-ldflags=( -L/usr/lib &&  \
make' )
}
which is syntactically invalid due to the presence of a '=' character
in the second line of the command property.
The fault is a consequence of this instruction
ini=( ${ini[*]/=/=\( } ) # convert item to array
which converts every first '=' of every line into '=( '. The trick
consists in making every values of ini properties a …
=> cqfd: simplify parsing for multi-line

cqfd, tests/01-cqfd_init
Building a docker image may takes a while.
When cqfd init is run, docker is turned to quiet mode and cqfd does not
display any activity. User may think the cqfd process is get stuck.
This patch adds the support for the quiet mode to cqfd, which propagates
the quiet to mode to docker if the option -q is set.
Now:
$ cqfd init
will display output from docker build, while:
$ cqfd -q init
will turn docker build into quiet mode and display nothing.
=> cqfd: add quiet mode option -q

cqfd, tests/01-cqfd_init
Under certain circumstances, our UID may be already taken by another
user into the container
$ cqfd -d
useradd: UID 1000 is not unique
Add the non-unique `-o' as it is already the case for groupadd.
=> cqfd: fix non unique user-id

Makefile, README.md, bash-completion, cqfd
**Auto-completion** makes life easier. Lets start by entering *cqfd* and then enter ```TAB```.
$ cqfd [TAB]
-b       -f       -h       help     --help   init     -q       release
run
Every *argument* (*options* and *functions*) handled by *cqfd* are *auto-completed*.
Now, enter a *dash* ```-``` then ```TAB```.
$ cqfd -[TAB]
-b      -f      -h      --help  -q
This time, only *options* handled by *cqfd* are *auto-completed*.
Lets start with *flavors*. Enter ```-b``` then ```TAB```.
$ cqfd -b [TAB]
centos  ubuntu
Every *flavors* from ```.cqfdrc``` resource file are *auto-completed*.
Select ```ubuntu``` for example.
Lets change the resource file. Enter ```-f``` then ```TAB```.
$ cqfd -b ubuntu -f [TAB]
AUTHORS              CHANGELOG            cqfd*                .cqfd/
cqfd.1.adoc …
=> Bash completion

cqfd
Get rid of it as the default docker configuration will most likely
result in cqfd's output be logged to journald/syslog, which will fill
with tons of blob data.
=> cqfd: don't use a log driver

cqfd
Courtesy of: Gaël
The construct `[...] && cmd` does not work well
for my bash 4.2.46(1) build x86_64 on CentOS 7.3.
The construct:
if [..]; then
fi
works well.
Signed-off-by: Philipp Skadorov <philipp.skadorov@gmail.com>
[gael.portay: add philipp signed-off and update my first name]
Signed-off-by: Gaël PORTAY <gael.portay@savoirfairelinux.com>
=> cqfd: replace boolean && with if-then

CHANGELOG
Also switch the versioning scheme to single-digits which makes more
sense.
=> update CHANGELOG for v4 release

cqfd
This option is required to avoid resorting to docker-compose
each time one needs to run a container with some published
ports. This is especially useful, for example, when one
needs to debug a program using gdbserver.
=> cqfd: add extra parameter to publish ports

.cqfd/ubuntu/Dockerfile, .cqfdrc, CHANGELOG.md, cqfd, tests/05-cqfd_run_home_env_var
Instead of printing a warning, terminate with an error in case the user
still uses a legacy environment variable. After testing in the real
world, we noticed many users didn't notice the warnings.
=> die on legacy option usage

CHANGELOG.md, README.md, cqfd, tests/05-cqfd_init_extra_env, tests/test_data/.cqfd/docker/Dockerfile.init_extra_env
To provide flexibility during day-to-day development tasks, the user may
set CQFD_EXTRA_BUILD_ARGS to add extra options to cqfd docker build
command.
It could be useful to rebuild without docker cache or setting http_proxy variables.
=> cqfd: add CQFD_EXTRA_BUILD_ARGS option

tests/06-cqfd_release
In the 06-cqfd_release file some test use the host cqfd command and not
the $cqfd command being tested. This can lead to test failures.
This commit fixes #75.
=> tests: do not use the host cqfd

CHANGELOG.md, README.md, bash-completion, cqfd, tests/05-cqfd_init_alt_ext
The -f option allow to use external configuration file but there was no
way to use external docker directories.
=> Add support for alternative and external cqfd files

cqfd
As the script is using the "set -e" option, if the "docker run" command
fails the temporary launcher file "$tmp_launcher" is never removed.
Using the "trap ... EXIT" command allow to always remove the temporary
launcher even if previous commands have failed.
=> cqfd: always remove the launcher

cqfd
proposed update for date format in cqfd:
- make cqfd work with date on macosx
- keep linux compatibility
=> Use generic date format for rfc3339

cqfd, tests/05-cqfd_run_c, tests/05-cqfd_run_c_flavor
Except for the default flavor command, do not override the command
defined in flavor by the one given with the run argument. Instead
concatenate the two command.
=> cqfd: add the run -c argument

cqfd, tests/03-cqfd_version
This suppresses the warning below:
Fixes:
egrep: warning: egrep is obsolescent; using grep -E
=> Use grep -E instead of egrep

README.md, cqfd
CQFD was able to use the user SSH configuration (known_hosts, config) but could not benefit from global settings. Simply bind the global configuration dir to match the SSH configuration the user is expecting.
=> cqfd: bind global ssh config

cqfd
The sudo command controls its tty but su creates a new session and it does not.
According to man su(1):
--session-command=command
Same as -c, but do not create a new session. (Discouraged.)
This replaces the use of the option -c by --session-command to let su uses the same session.
=> cqfd: use su option --session-command

cqfd
The option -c hides the misconfiguration if the command= is unset and the option -c and its argument are given to the command-line.
This fixes commit 5ea905903c6161d20a25fad43a55071d271254e7.
=> cqfd: raise error if command= is unset but -c given

tests/test_data/.cqfd/centos/Dockerfile
CentOS is discontinued.
Its Docker images are still available but the mirrors of the package repositories are dying one after the others.
As a consequence, installing or updating packages lasts like an eternity before the process ends with succeed or fails.
This strips down the centos Dockerfile to the bare minimun as there is no reason to test for update packages.
=> tests: strip down centos7 Dockerfile

bash-completion
The cqfd bash-completion script completes the run command as follow:
- the argument following the run command completes for an host executable via `compgen -c` Note: this is correct at the exception it completes for an executable in the host system instead of the container
- the arguments following the run command executable completes for the cqfd arguments, instead of completing for the run command executable arguments
Here is an example:
$ cqfd run fdisk [hit tab]
-b         -f         --help     -q         -V
-C         flavors    help       release    --version
-d         -h         init       run        version
And what it is expecting:
$ cqfd run fdisk [hit tab]/dev/
/dev/sda
/dev/sda1
/dev/sda2
/dev/sdb
/dev/sdb1
This uses the bash-completion function _command_offset() to complete …
=> bash-completion: fix completion for run arguments

cqfd
Most of the functions in the script do not use a space between the name and the parenthesis, and opens the curving brace in the same line.
This fixes syntax by removing the spaces between the function name and its parenthesis and opening the curging brace in the same line for the sake of consistancy.
=> cqfd: fix syntax

cqfd
The function docker_run() takes a single argument as the command string, but it uses "$@". Therefore, $1 is enough and it should be used instead to avoid confusion.
The shell expression "$@" expands to an array string, but the "$@" is assigned to the scalar (i.e. non-array) variable build_cmd_alt; Therefore, $* should be used instead.
This uses $1 and $* instead of "$@" at some places.
=> Use $1 and $* instead of "$@"

README.md, bash-completion, cqfd
The user `~/.ssh` config forwarding is now controlled by the `CQFD_NO_USER_SSH_CONFIG` environment variable. This allows finer control over the ssh configuration forwarding.
=> More options for SSH, GIT and SHELL

tests/05-cqfd_init_custom_image, tests/05-cqfd_run_c, tests/05-cqfd_run_c_flavor, tests/05-cqfd_run_su_or_sudo_backend, tests/test_data/.cqfd/centos/Dockerfile, tests/test_data/.cqfd/docker/Dockerfile, tests/test_data/.cqfd/docker/Dockerfile.build_context, tests/test_data/.cqfd/docker/Dockerfile.init_extra_env, tests/test_data/.cqfd/docker/Dockerfile.missing_dependencies
This commit brings 10 years of Ubuntu updates to the tests, and small syntax updates for docker not to complain.
=> tests: update Dockerfiles

README.md, cqfd
This patch adds a new option to the archive name template: %Du. It expands to the current Unix timestamp.
=> release: add %Du option for unix timestamp in archive name

cqfd, tests/03-cqfdrc_error
Hello,
This fixes some issues found in the mechanism of ini-translation-to-bash.
I am a bit worry if the fix about the removal of (single) space before sign `=`, or after sign `=` (but not both) and if true tabulation before and after the sign `=` will break things to users since it never worked.
Maybe, we could simply drops that feature of stripping (single) whitespaces arround `=`.
What do you think?
=> Few parse_ini_config_file() fixes

README.md, bash-completion, cqfd, tests/07-cqfd_exec, tests/08-cqfd_shell
Hello,
This PR adds two commands:
`cqfd shell` opens an interactive shell from within the container. It is compliant with the [sh(1)](https://man7.org/linux/man-pages/man1/sh.1p.html) as it runs `$SHELL` underneath. For example: `cqfd shell -c "cat /etc/os-release"` outputs the distribution release from the container. It is an alternative to `cqfd run` that is  too restricted by running somehow `/bin/sh -c` with a list of arguments that is hard to operate with.
`cqfd exec COMMAND [ARGUMENTS]` runs the given command from within the container. Fox example: `cqfd exec cat /etc/os-release` outputs the distribution release from the container. It tries to address #99, `cqfd exec git commit -m "A multiple word commit message not breaking command"` 
Ping me if it makes sense.
Regards,
Gaël
=> Add shell and exec commands

tests/05-cqfd_run_command
I guess the word with makes more sense here, since it tests the run command with arguments.
=> tests: fix typo

bash-completion
This fixes commit 14dba6973935dcdf34e787aa6c594ba12274c5bf.
The shell grammar of the well-known shells (i.e. bash, dash, ash, ksh) does not allow empty functions; however, zsh does.
This adds the null command to fix a violation of the shell grammar.
Fixes:
source /usr/share/bash-completion/completions/cqfd
/usr/share/bash-completion/completions/cqfd: line 20: syntax error near unexpected token `}'
/usr/share/bash-completion/completions/cqfd: line 20: `	}'
=> Fix "bash-completion: improve compatibility with zsh"

tests/05-cqfd_init_extra_env, tests/05-cqfd_run_extra_groups, tests/05-cqfd_run_extra_hosts, tests/05-cqfd_run_whitespace_resiliency, tests/06-cqfd_release, tests/09-cqfd-pts
This reverts commit 0cef50e9a93545c91b2beaf9842f76fafcd235d3 once again.
The commit e8bc9afb3381800c7f92045c6aa26f167802baa6 has mistakenly reverted the change ae5c830e236466fc5d8ad42e6eca19bf371945db.
=> Revert "cqfd: redirect command stderr to stdout" once again

README.md, tests/08-cqfd_shell, tests/test_data/Makefile, tests/test_data/whereami.sh
The good point in having a shell CLI is to be able to run shell scripts, either directly as a interpreter or indirectly via other binaries.
This documents all of this in the README.md.
=> doc: use cqfd shell as interpreter or shell in binaries

tests/08-cqfd_shell
This ensures to use cqfd installed in the TDIR instead of the one installed in host system.
Fixes (if cqfd is not available in PATH):
$ make test
(...)
[10:48:06|notice] preparing "cqfd shell is usable as a shell interpreter script"
[10:48:06|info] result: cqfd shell is usable as a shell interpreter script: FAIL
/usr/bin/make
[10:48:06|notice] preparing "cqfd shell is usable as a shell interpreter in binaries"
[10:48:06|info] result: cqfd shell is usable as a shell interpreter in binaries: FAIL
(...)
**|FAIL|cqfd shell is usable as a shell interpreter script
**|FAIL|cqfd shell is usable as a shell interpreter in binaries
(...)
--------------------
make[1]: Leaving directory '/home/gportay/src/cqfd/tests'
=> tests: 08-cqfd_shell: use cqfd from TDIR

cqfd
The function parse_ini_config_file() modifies (i.e. sets) the variable IFS[1] and does not restore it.
As a consequence, the function modifies the word splitting[2] for the entire script after it is called. The "words" are split by lines and "breaks" the default word splitting by whitespaces.
This makes the variable IFS local to the function so the previous value is automatically "restored" once the function exits.
[1]: https://www.gnu.org/software/bash/manual/bash.html#index-IFS
[2]: https://www.gnu.org/software/bash/manual/html_node/Word-Splitting.html
=> cqfd: restore IFS after call to parse_ini_config_file()

README.md
This fixes the example of run -c by adding the missing command run, and precise the option -c is immediately after the command run.
=> README.md: fix run -c example

README.md, cqfd, tests/05-cqfd_init_extra_hosts
This enables declaring a set of arguments to use with 'docker build', as
a declarative complement to CQFD_EXTRA_BUILD_ARGS.
See https://github.com/savoirfairelinux/cqfd/commit/4c5018173fe0fc6c7dcd8a48bae57fc131138bfe.
Fixes: #153
=> cqfd: add support for the 'docker_build_args' build option

README.md
This marks the property flavors as deprecated.
See 253b96a52593a6b9d4a5d7ec6646b4866125cf85 and
01260e78c946dbf9473dd5915500059c14194fba.
=> README.md: depreciate flavors property

tests/05-cqfd_run_extra_groups, tests/09-cqfd-pts, tests/Makefile, tests/jtest.inc
Currently, when a test is failing, the CI does not fail because the script does not detect correctly a failure.
This commit makes the test of a failing test more explicit
=> ci: make failing tests fail the CI

.github/workflows/makefile.yml, Makefile, cqfd
This is a first pass of shellcheck fixes.
It fixes the trivial errors and disables the more tricky ones for now.
=> Shellcheck first pass

.github/workflows/makefile.yml, Makefile, cqfd, tests/06-cqfd_release
The git-log commands run to replace the git templates (short or long hash of the last commmit) fail during the tests, as the test cd to another directory, and thus left the git repository.
The error fails silently and it does not break the execution of cqfd because the local declaration and the assignment are both performed simultaneously, masking the returned value. See shellcheck errors below:
In cqfd line 301:
local git_short=$(git rev-parse --short HEAD 2>/dev/null)
^-------^ SC2155 (warning): Declare and assign separately to avoid masking return values.
In cqfd line 302:
local git_long=$(git rev-parse HEAD 2>/dev/null)
^------^ SC2155 (warning): Declare and assign separately to avoid masking return values.
In cqfd line 303:
local date_rfc3339=$(date +"%Y-%m-%d")
^----------^ SC2155 …
=> Makefile: tests: set GIT_DIR

tests/08-cqfd_shell
The commit 41732153f5e61b4c12413a3c6a103501b2a99140 has introduced the skip result.
This logs the skipped test if make is not installed.
=> tests: 08-cqfd_shell: log skipped test

.github/workflows/makefile.yml, cqfd
The docker run -v option creates a directory if the path specified as a source does not exists, whereas the --mount option does not, and is recommended by Docker over --volume
=> ci: do not create .gitconfig dir

cqfd
This rewrites the function parse_ini_config_file() to address the
shellcheck error SC2206[1].
[1]: https://www.shellcheck.net/wiki/SC2206
=> cqfd: rewrite parse_ini_config_file()

README.md, cqfd, tests/10-cqfd_doutofd, tests/test_data/.cqfd/docker/Dockerfile.doutofd
This provides an example on how to run cqfd with docker-out-of-docker.
See #136.
=> tests: add testing for docker-out-of-docker

tests/05-cqfd_run_extra_groups
This fixes commit ae619157e57db40049371abfbdd7958349b6ca5a.
=> Fix "tests: use bash option pipefail"

cqfd
This adds the sh option errexit so that the launcher script exits
immediately if a pipeline, a list, or a compound command exits with a
non-zero status.
According to bash(1):
SHELL BUILTIN COMMANDS
set [-abefhkmnptuvxBCEHPT] [-o option-name] [--] [-] [arg ...]
set [+abefhkmnptuvxBCEHPT] [+o option-name] [--] [-] [arg ...]
(...)
-e
Exit immediately if a pipeline (which may consist of a single
simple command), a list, or a compound command (see SHELL
GRAMMAR above), exits with a non-zero status. The shell does not
exit if the command that fails is part of the command list
immediately following a while or until keyword, part of the test
following the if or elif reserved words, part of any command
executed in a && or || list except the command following the
final && or ||, any command in a …
=> cqfd: add sh option errexit

cqfd
This avoids unnecessary testing the support for the su option
--session-command if sudo is in use.
=> cqfd: launcher: do not test for --session-command if using sudo

README.md, cqfd
This adds the environment CQFD_DOCKER to set the docker binary. It
allows to run the client using sudo(8).
=> cqfd: add CQFD_DOCKER option

tests/10-cqfd_doutofd
The Ubuntu version number can be updated so we include a regex in the
grep statement
=> tests: fix grep in doutofd

tests/Makefile
cqfd uses several environment variables and the integration tests test them.
Therefore, the testing environment alters the tests if these environment are set to some values.
This resets all the CQFD_ environment variables to empty values to prevent the testing environment to polute the tests.
Important: These variables remain overridable thanks to the make command line. The command below runs the test using podman backend:
$ make CQFD_DOCKER=podman
=> tests: reset CQFD_ environment to empty values

cqfd, tests/05-cqfd_run_check_dependencies, tests/05-cqfd_run_su_or_sudo_backend
With my recent work on the launcher, I figured out that it is not trivial to enable the debug traces from the CLI as it requires to set the `CQFD_DEBUG` environment to `1` either using the docker-run option `--env CQFD_DEBUG=1` or using the Dockerfile directive `ENV CQFD_DEBUG=1`.
This PR suggests to enable these launcher traces either using `--verbose` (first commit) or using `--verbose` twice (second commit) to preserve the existing behavior that wants to set `CQFD_DEBUG=1` in the container environment (poluting the environment at the same time).
=> Propagate verbose to launcher

cqfd
This stops to append the distro to the custom image as it is not necessary.
=> cqfd: custom_img_name: do not append distro

cqfd, tests/03-cqfdrc_error
Hello,
Surprisingly, I found commits of an old age in my repository :)
With this PR, I check if the sections `[project]` and `[build]` (including eventually the flavor section), and `cqfd` die with an appropriate message, as soon as possible.
Also, I check it the required properties `org`, `name` and `command` are set, and die as soon as possible.
The user is guided by the messages to build its own `.cqfdrc` file; i.e. hitting the wall one after the other.
Additionally, I have modified the ini parser even more by simplifying the translation the .ini to shell (using keyword `function` that do not need the parenthesis). Also, the parser, allows to parse empty files and empty sections.
Of courses, I have added more tests for these changes ;)
Kind Regards,
Gaël
=> Simplify ini parsing once again

tests/00-setup, tests/01-cqfd_init, tests/03-cqfd_error, tests/03-cqfd_help, tests/03-cqfd_version, tests/05-cqfd_init_alt_ext, tests/05-cqfd_init_custom_image, tests/05-cqfd_init_extra_env, tests/05-cqfd_init_flavor, tests/05-cqfd_run, tests/05-cqfd_run_c, tests/05-cqfd_run_c_flavor, tests/05-cqfd_run_check_dependencies, tests/05-cqfd_run_command, tests/05-cqfd_run_config, tests/05-cqfd_run_flavor, tests/06-cqfd_release
Most of the tests check for the success conditions, i.e, the test succeeds in the if statement (pass), and the test fails in the else statement (fail):
if cqfd ...; then # or ! cqfd ...
echo "yeah, test has passed!"
else
echo "oops, test has FAILED!"
fi
However, some tests do not:
if cqfd ...; then # or ! cqfd ...
echo "oops, test has FAILED!"
else
echo "yeah, test has passed!"
fi
This turns the test logic to "if all needed conditions to succeed the test are met, then the test passes, otherwise if any of the conditions is unmet, then the test fails".
It reverses some test logics so all the tests look similar and expect to pass in the if statement (and thus, fail in the else statement).
=> tests: reverse some test logic

tests/05-cqfd_run_extra_groups, tests/08-cqfd_shell, tests/09-cqfd-pts, tests/10-cqfd_doutofd
Some of the skip tests check for if the test has to be skipped first,
i.e, the test is skipped in the if statement (pass), and the test is
tested in the else statement (fail).
This reverses some skip test logics so all the tests look similar and
expect to be skipped in the if statement (and thus, to be tested in the
else statement).
=> tests: reverse some test skip logic

cqfd, tests/05-cqfd_run_home_env_var
cqfd provides two ways to set extra docker-run argument, either from the
environment via the variable CQFD_EXTRA_RUN_ARGS, or from the .cqfdrc
file via the build option docker_run_args.
cqfd checks if the HOME environment is overriden by the docker-run
option --env using the environment variable CQFD_EXTRA_RUN_ARGS.
However, cqfd does not checks if it is overriden by the build option
docker_run_args.
This adds the missing checks for overriding the HOME environment using
build option docker_run_args.
=> cqfd: fix overriding HOME environment from docker_run_args

bash-completion, cqfd
This adds the options --release that allows to cqfd release from an
empty command and the command run.
cqfd [--release] [run] [command_string].
=> cqfd: optionize release command

cqfd, tests/03-cqfdrc_error
The .cqfdrc file is not loaded and the warning below always poutputs even if command= is set to an non-empty string:
$ cat .cqfdrc
[project]
name=test
org=test
[build]
command=true
$ cqfd run -c true
cqfd: warning: .cqfdrc: Missing or empty build.command property
This fixes commit 6dd7415ac41376aafc0581237ebbd1647d420bcb.
=> Fix "cqfd: add warning if run -c with build.command unset"

cqfd, tests/05-cqfd_run_dockerfile
cqfd does not run its launcher script if the image used has its own
entrypoint set in the Dockerfile.
This sets the launcher as the container ENTRYPOINT, i.e. it runs it as
the container executable and it overwrites the default ENTRYPOINT of the
image if set.
=> cqfd: launcher: use option --entrypoint

.cqfd/deb/Dockerfile
Debian 13 (Trixie) was relesed today[1].
This tags bookworm instead of latest (trixie) as the base image for the Dockerfile.
Note: The GitHub Workflow uses bookworm.
[1]: https://www.debian.org/releases/trixie/
=> debian: Dockerfile: use tag bootworm

tests/Makefile
mktemp(1) replaces the TEMPLATE (/tmp/tmp.XXXXXX) by letters **AND**
digits, even if its man-page does not mention it clearly.
As a consequence, the test directory is not be removed if it starts by a
digit.
This fixes the uncleaned directory by adding the missing digit range to
the regex pattern.
Fixes:
$ make test
(...)
$ ls -ld /tmp/cqfd-test.*
drwxrwxr-x 3 gportay gportay 4096 Aug  9 17:13 /tmp/tmp.9gbPXP
Note: Additionally, it enforces the regular expression by adding the
repetition operator +.
From grep(1):
Repetition
A regular expression may be followed by one of several
repetition operators:
?      The preceding item is optional and matched at most once.
*      The preceding item will be matched zero or more times.
+      The preceding item will be matched one or more times.
{n} …
=> tests: fix uncleaned temporary directory

tests/00-setup, tests/01-cqfd_init, tests/03-cqfd_error, tests/03-cqfd_help, tests/03-cqfd_version, tests/03-cqfdrc_error, tests/05-cqfd_init_custom_image, tests/05-cqfd_run_config, tests/06-cqfd_release
This PR fixes two nitpicks:
The first nitpick double-quotes the whole string including the variable name `$TDIR`, as the most of test files:
``` diff
-cqfd="$TDIR"/.cqfd/cqfd
+cqfd="$TDIR/.cqfd/cqfd"
```
The second nitpick updates the project.org to `cqfd' for [tests/03-cqfdrc_error] so every built containers use the exact same tag, and thus, every built containers are similar and easily remarkable:
cqfd_<user>_cqfd_test_<hash>[_<distro>]
=> tests: more nitpicks

tests/10-cqfd_doutofd
The -i (interactive) flag was previously added to docker run, but it is not needed when the command only outputs a file to stdout.
In GitHub Actions, workflows are executed with pipes connected to stdin, stdout, and stderr. Because stdin is a pipe, running docker run -ti fails.
This change removes the unnecessary -i option, ensuring the test "cqfd run docker using host docker daemon" works correctly in CI environments.
Fixes:
[18:30:29|notice] preparing: "cqfd run docker using host docker daemon"
#0 building with "default" instance using docker driver
(...)
(+ docker run --privileged --rm --log-driver=none --env HOME=/home/runner --volume /home/runner/.ssh:/home/runner/.ssh --volume /etc/ssh:/etc/ssh --volume /var/run/docker.sock:/var/run/docker.sock --volume …
=> tests: 10-cqfd_doutofd: drop unnecessary option -i
